# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88fecc5208a17056f85816b6d081f9c28764c04d7d3586c6f406b8cc3fd3b482f126b638c925c7d0864c51f687da0e06bf17177441812f8f4b2651a0cbc6312b

test:
  secret_key_base: 1b8d2caa9e1004c010a5c659eba9d0be256bcb6877362bf756dfc7f552ed790b7f7cb94e20b6fa4f9db9218f269ee1110a063b3eb761888c30e60b1c300a5519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
